services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - "8081:8081"
  api:
    restart: always
    image: mangila/spring-reactive-mongodb
    ports:
      - "8080:8080"
    depends_on:
      - mongo